;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 2.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.015000|            5|
;+----------------------------------------+

M48

METRIC,LZ,00.0000
T01C0.015000
%
M71
G90
T01
X09893Y-157
X18545Y-128
X358504Y-063263
X343504Y-157277
X247261Y-031656

M30
