;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 2.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.300000|            6|
;+----------------------------------------+

M48

METRIC,LZ,00.0000
T01C0.300000
%
M71
G90
T01
X-185213Y075094
X101939Y-054865
X185483Y101517
X263423Y067981
X250423Y-072833
X161083Y101517

M30
